### ISSUE TITLE
Clothing State Menu's 'All accs' button stopped working

### ISSUE THREAD

**Issue by TheLX5** [Madevil/KK_AccStateSync#4]
The buttons to turn on or off every accesory in the currently loaded character stop working if I use a KK_AccStateSync version newer than 3.0.0.0. I've tried every recent release and they all have the same issue.

![image](https://user-images.githubusercontent.com/17969056/114856605-2835b700-9d9c-11eb-86a5-a33981af54d4.png)

Everything else works as expected.

[output_log.txt](https://github.com/Madevil/KK_AccStateSync/files/6317249/output_log.txt)

**Comment by Madevil** [comment]
Not a bug, this is part of the design in order to prevent meaningless accessories visibility toggles multiple loops when you click on and switch to another acc slot.

Switching off the "Force Preview" toggle in the right hand sidebar would unblock them.
