### ISSUE TITLE
Don't work with latest MoreAccessories

### ISSUE THREAD

**Issue by EveKaczmarek** [Madevil/KK_AccStateSync#5]
Don't work with MoreAccessories 2.0.10
https://github.com/jalil49/MoreAccessories/releases/tag/2.0.10

`[Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
Type System.Collections.Generic.Dictionary<string, Type>.get_Item(string)
void AccStateSync.AccStateSync.Start()`
[output_log.txt](https://github.com/Madevil/KK_AccStateSync/files/7267310/output_log.txt)

AccStateSync button in Maker simply doesn't work, accessories doesn't sync as well. Rollback to MoreAccessories 1.1.0 resolved this problem.

**Comment by Madevil** [comment]
I think I've made myself pretty clear

"**don't ask me to support some freaking shit which is not even halfway finished**"

**Comment by EveKaczmarek** [comment]
I'm sorry? Updated KK_Plugins REQUIRED this overhaul (version 2.0 and up) to work normally, otherwise MoreAccessiories don't load additional slots from cards.

**Comment by Madevil** [comment]
I wonder if you actually read the description of it

`Koikatu (KK/KKP) and EC users will need to update MoreAccessories to the new experimental version. Some plugins are not yet compatible with this update, so only update if you know what you're doing (no need to update for now). You can see a list of plugins that might still have issues here. There might still be some bugs in the new MoreAccessories or this version of KKAPI, so be on a lookout.`

If you choose to install it and break your game client, it's your choice, learn to take responsibility with your own action like an adult.

**Comment by EveKaczmarek** [comment]
Okay, I'll wait for for next updates.
Have a good day.
